services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: db_v1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

  db_shadow:
    image: postgres:17
    container_name: db_shadow
    environment:
      POSTGRES_DB: db_v1_shadow
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - '5434:5432'
    volumes:
      - db_shadow_data:/var/lib/postgresql/data
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4:9.3
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - db_network

volumes:
  db_data:
  db_shadow_data:

networks:
  db_network:
    driver: bridge
